default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget-app_development
  username: postgres
  password: domain-101

test:
  <<: *default
  database: budget-app_test
  username: postgres
  password: domain-101

production:
  <<: *default
  database: bdget_application_production
  username: budget_application
  password: <%= ENV["BUDGET_APPLICATION_DATABASE_PASSWORD"] %>
